# This is a basic workflow to help you get started with Actions

name: Build a Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  release:
    types: published


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build the Release
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "I am going to build the release and add content to the release notes."

      - name: Install Dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        
      - run: |
          npm install @actions/github
      
      - name: Edit Release
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const { owner, repo } = context.repo;
            const release_id = context.payload.release.id;
            const { GitHub: GitHubAPI } = require("@actions/github");
            const gh = new GitHubAPI(process.env.GITHUB_TOKEN);
            const { data: release } = await gh.repos.getRelease({ owner, repo, release_id });
            const body = release.body + "\n\nAdd your new content here.";
            await gh.repos.updateRelease({ owner, repo, release_id, body });